source/urls.py
from django.contrib import admin
from django.urls import path, include
# from personal_blog.views.post_views import
from source.view import IndexView, index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', IndexView.as_view(), name ="home_page"),
    path('', index, name = "home_page"),
    path('post/', include('personal_blog.urls.post_urls')),
    path('author/', include('personal_blog.urls.author_urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # связывает с путем до нашей папки с медиа файламы, где наши медиа данные будут хранится

personal_blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User

from personal_blog.helpers.validators import at_least_3


class Author(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, related_name='authors')

    def __str__(self):  # method str like in java
        return f"{self.pk}. {self.name}"


class Post(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name="Header")
    body = models.TextField(max_length=3000, null=False, blank=False, verbose_name="Body of the post",
                            validators=[at_least_3, ])
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, related_name='posts', default=1)
    tags = models.ManyToManyField('personal_blog.Tag', related_name='posts', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Data")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated Data")

    def __str__(self):  # method str like in java
        return f"{self.pk} - {self.title} by {self.author}"

    class Meta:
        permissions = [
            ('can_view_posts', 'Can view posts')
        ]


class Comment(models.Model):
    text = models.TextField(max_length=1000, null=False, blank=False, verbose_name='Comment')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, related_name='comments', default=1)
    post = models.ForeignKey('personal_blog.Post', on_delete=models.SET_DEFAULT, default=1, related_name='Comments', verbose_name="Post")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Data")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated Data")

    def __str__(self):
        return f"{self.text[:20]} by {self.author}"


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name="Name")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created Data")

    def __str__(self):
        return f"{self.name}"

# ORM ->  это способ обращаться к баззу данных без использование sql запросы
# all of this are look ups
# Post.objects.filter(id__lte = 4) -> только 4 обьекта как limit 4

# Post.objects.filter(title__icontains = 'Crime')
# startswith

personal_blog/helpers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, TemplateView, DetailView


class ParamMixin():
    form_class = None
    template_name = None
    model = None
    redirect_url = ''
    context_key = 'objects'
    key_kwarg = 'pk'

    def get_redirect_url(
            self):  # просто геттер для url - ну например с помощью этого мы можем брать 'home_page', 'post_create'-> вот такие url имена мы можем брать
        return self.redirect_url

    def get_object(self):
        pk = self.kwargs[self.key_kwarg]
        return get_object_or_404(self.model, pk=pk)


class CustomFormView(View, ParamMixin):  # мы импортируем здесь generic view и с этого и мы построили свой FormView
    form_class = None  # передаем туда класс формы например у нас есть формы: PostForm, CommentForm, AuthorForm вот этих то мы и передаем здесь
    template_name = None  # мы будем сюда передовать путь шаблона -> html страница
    redirect_url = ''  # ссылка для перенапровление

    def get(self, request, *args, **kwargs):  # метод для обработки get запросов
        form = self.form_class()  # наша форма -> PostForm, AuthorForm ...
        context = self.get_context_data(
            form=form)  # контекст функция getter должны передовать форму чтоб мы в шоблоне могли работать
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):  # для работы с post запросами
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(
                form)  # это метод который мы сами будем создать для того чтоб если форма валидна выполнялась эта функция
        else:
            return self.form_invalid(
                form)  # это точно также если у нас форма не валидна то есть есть ошибки в форме то мы будем вызвать этот метод инвалид

    def form_valid(self, form):
        return redirect(self.get_redirect_url())  # перенаправляем на url адрес если наша форма валидна

    def form_invalid(self,
                     form):  # форма не прошел валидацию в этом случае мы должны render to smt like this { return render(request, 'posts/create.html', context = context) }
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_context_data(self, **kwargs):  # **kwargs это именованный аргумент, словарь с аргументами key and value
        return kwargs


class CustomListView(TemplateView, ParamMixin):
    model = None  # даем имя модели
    context_key = 'objects'  # имя шаблона

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.model.objects.all()
        return context

    def get_objects(self):
        return self.model.objects.all()


class CustomDetailView(TemplateView, ParamMixin):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context


class CustomCreateView(View, ParamMixin):
    form_class = None
    template_name = ''
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)


class CustomUpdateView(View, ParamMixin):
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object)
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def get_context_data(self, **kwargs):
        context = self.kwargs.copy()
        context[self.context_key] = self.object
        context.update(kwargs)
        return context

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, {'context': context})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class CustomDeleteView(View, ParamMixin):
    confirm_deletion = True

    def get(self, request, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        self.perform_deletion()
        return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        

templates/partials/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home_page' %}">MyBlog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_list' %}">Post List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home_page' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_create' %}">Add Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'author_list' %}">Authors List</a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'author_create' %}">Add Author</a>#}
{#                </li>#}
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-outline-primary" href="{% url 'login' %}?next={{ request.GET.next }}">Log-in</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success" href="{% url 'register' %}?next={{ request.GET.next }}">Register</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false" style="color: #ff6600; font-weight: bold;">
                        Hello, {{ request.user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'user_detail' user.pk %}" style="color: #ff6600; font-weight: bold;">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'user_edit' %}" style="color: #ff6600; font-weight: bold;">Edit Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'password_change' %}" style="color: #ff6600; font-weight: bold;">Change Password</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}?next={{ request.GET.next }}" style="color: #ff6600; font-weight: bold;">Log-out</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/partials/pagination.html
<div class="pagination">


    <span class="step-links">
        <a href="?page=1">&laquo; first</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% else %}
            <span class="page-disabled">previous</span>
        {% endif %}

        <form class="current-page" method="get">
            <label for="page">
                Page <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                of {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% else %}
            <span class="page-disabled">next</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    </span>
</div>

templates/partials/post_form.html
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Update Post</h4>
                </div>
                <div class="card-body">
                    <form  method="POST">
                        {% csrf_token %}
                        {% for error in non_field_errors %}
                            <p class="form-error">{{ error }}</p>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="id_title" class="form-label">Title:</label>
                            <input type="text" name="title" id="id_title" class="form-control" value="{{ post.title }}">
                            {% for error in form.title.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_body" class="form-label">Body:</label>
                            <textarea name="body" id="id_body" class="form-control" rows="5">{{ post.body }}</textarea>
                            {% for error in form.body.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_tags" class="form-label">Tags:</label>
                            {{ form.tags }}
                        </div>
                        {% if form.cleaned_data.title == form.cleaned_data.body %}
                            <p class="text-warning">Post title and body cannot be the same</p>
                        {% endif %}
{#                        <button type="submit" class="btn btn-primary mt-3">Update</button>#}
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Create New Tag</h4>
                </div>
                <div class="card-body">
                    <form action="{% url 'tag_create' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_name" class="form-label">Name:</label>
                            <input type="text" name="name" id="id_name" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary">Create Tag</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/post_list.html
{% if is_paginated %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% include 'partials/pagination.html' %}
            </div>
        </div>
    </div>
{% endif %}

<div class="container mt-4">
    <div class="row">
        {% for post in posts %}
            <div class="col-md-8 mx-auto mb-4">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title"><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h3>
                        <p class="card-text">
                            <small class="text-muted">
                                <a href="{% url 'user_detail' post.author_id %}">{{ post.author }}</a> |
                                {{ post.updated_at|date:"d.m.Y H:i:s" }}
                            </small>
                        </p>
                        <p class="card-text">Published at: {{ post.created_at|date:"d.m.Y H:i:s" }}</p>

                        {% if perms.posts.change_post and post.author == request.user %}
                            <a href="{% url 'post_update' post.pk %}" class="btn btn-sm btn-primary">Update</a>
                        {% endif %}
                        {% if perms.posts.delete_post and post.author == request.user %}
                            <a href="{% url 'post_delete' post.pk %}" class="btn btn-sm btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-md-8 mx-auto">
                <p class="text-center">No posts</p>
            </div>
        {% endfor %}
    </div>
</div>

{% if is_paginated %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% include 'partials/pagination.html' %}
            </div>
        </div>
    </div>
{% endif %}

templates/partials/search.html
<form action="" class="d-flex" method="GET">
    <input type="text" name="search" class="form-control" placeholder="Search">
    <button type="submit" class="btn btn-outline-success">Search</button>
    {% for error in form.search.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
</form>

templates/partials/user_forms.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="multipart/form-data">
        {% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
    <div class="alert alert-danger">{{ error }}</div>
{% endfor %}


{% for field in form %}
    <div class="form-group">
        <div class="input-group mb-3">
            <span class="input-group-text">{{ field.label }}</span>
            {{ field }}
        </div>
    </div>
    {% for errors in field.errors %}
        <p class="text-danger">{{ errors }}</p>
    {% endfor %}
{% endfor %}


{% if not fields_only %}
    <button type="submit" class="btn btn-success">{{ button_text|default:"Submit" }}</button>
    </form>
{% endif %}